/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxy from "./proxy";
export { AuthenticatedProxy__factory } from "./AuthenticatedProxy__factory";
export { OwnableDelegateProxy__factory } from "./OwnableDelegateProxy__factory";
export { ProxyRegistry__factory } from "./ProxyRegistry__factory";
export { ProxyRegistryInterface__factory } from "./ProxyRegistryInterface__factory";
export { TokenRecipient__factory } from "./TokenRecipient__factory";
