/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ProxyRegistryInterface,
  ProxyRegistryInterfaceInterface,
} from "../../../contracts/registry/ProxyRegistryInterface";

const _abi = [
  {
    inputs: [],
    name: "delegateProxyImplementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "proxies",
    outputs: [
      {
        internalType: "contract OwnableDelegateProxy",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ProxyRegistryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ProxyRegistryInterfaceInterface {
    return new utils.Interface(_abi) as ProxyRegistryInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ProxyRegistryInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ProxyRegistryInterface;
  }
}
