/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StaticERC1155 } from "./StaticERC1155";
export type { StaticERC20 } from "./StaticERC20";
export type { StaticERC721 } from "./StaticERC721";
export type { StaticUtil } from "./StaticUtil";
