/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StaticERC1155__factory } from "./StaticERC1155__factory";
export { StaticERC20__factory } from "./StaticERC20__factory";
export { StaticERC721__factory } from "./StaticERC721__factory";
export { StaticUtil__factory } from "./StaticUtil__factory";
