/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface StaticMarketInterface extends utils.Interface {
  functions: {
    "ERC20ForERC721(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "ERC721ForERC20(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "anyERC1155ForERC20(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "anyERC20ForERC1155(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "anyERC20ForERC20(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "name()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ERC20ForERC721"
      | "ERC721ForERC20"
      | "anyERC1155ForERC20"
      | "anyERC20ForERC1155"
      | "anyERC20ForERC20"
      | "name"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ERC20ForERC721",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ERC721ForERC20",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anyERC1155ForERC20",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anyERC20ForERC1155",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anyERC20ForERC20",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ERC20ForERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC721ForERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anyERC1155ForERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anyERC20ForERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anyERC20ForERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;

  events: {};
}

export interface StaticMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StaticMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ERC20ForERC721(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    ERC721ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    anyERC1155ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    anyERC20ForERC1155(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    anyERC20ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    name(overrides?: CallOverrides): Promise<[string]>;
  };

  ERC20ForERC721(
    extra: PromiseOrValue<BytesLike>,
    addresses: PromiseOrValue<string>[],
    howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    uints: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    counterdata: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ERC721ForERC20(
    extra: PromiseOrValue<BytesLike>,
    addresses: PromiseOrValue<string>[],
    howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    uints: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    counterdata: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  anyERC1155ForERC20(
    extra: PromiseOrValue<BytesLike>,
    addresses: PromiseOrValue<string>[],
    howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    uints: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    counterdata: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  anyERC20ForERC1155(
    extra: PromiseOrValue<BytesLike>,
    addresses: PromiseOrValue<string>[],
    howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    uints: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    counterdata: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  anyERC20ForERC20(
    extra: PromiseOrValue<BytesLike>,
    addresses: PromiseOrValue<string>[],
    howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    uints: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    counterdata: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ERC20ForERC721(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC721ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyERC1155ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyERC20ForERC1155(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyERC20ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ERC20ForERC721(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC721ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyERC1155ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyERC20ForERC1155(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyERC20ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC20ForERC721(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC721ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyERC1155ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyERC20ForERC1155(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyERC20ForERC20(
      extra: PromiseOrValue<BytesLike>,
      addresses: PromiseOrValue<string>[],
      howToCalls: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      uints: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      counterdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
