/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnedUpgradeabilityProxy } from "./OwnedUpgradeabilityProxy";
export type { OwnedUpgradeabilityStorage } from "./OwnedUpgradeabilityStorage";
export type { Proxy } from "./Proxy";
