/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxy from "./proxy";
export type { proxy };
export type { AuthenticatedProxy } from "./AuthenticatedProxy";
export type { OwnableDelegateProxy } from "./OwnableDelegateProxy";
export type { ProxyRegistry } from "./ProxyRegistry";
export type { ProxyRegistryInterface } from "./ProxyRegistryInterface";
export type { TokenRecipient } from "./TokenRecipient";
