/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface AuthenticatedProxyInterface extends utils.Interface {
  functions: {
    "initialize(address,address)": FunctionFragment;
    "proxy(address,uint8,bytes)": FunctionFragment;
    "proxyAssert(address,uint8,bytes)": FunctionFragment;
    "receiveApproval(address,uint256,address,bytes)": FunctionFragment;
    "registry()": FunctionFragment;
    "revoked()": FunctionFragment;
    "setRevoke(bool)": FunctionFragment;
    "upgradeabilityOwner()": FunctionFragment;
    "user()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "initialize"
      | "proxy"
      | "proxyAssert"
      | "receiveApproval"
      | "registry"
      | "revoked"
      | "setRevoke"
      | "upgradeabilityOwner"
      | "user"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "proxy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proxyAssert",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveApproval",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(functionFragment: "revoked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRevoke",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeabilityOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "user", values?: undefined): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proxy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxyAssert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRevoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeabilityOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;

  events: {
    "ReceivedEther(address,uint256)": EventFragment;
    "ReceivedTokens(address,uint256,address,bytes)": EventFragment;
    "Revoked(bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReceivedEther"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedTokens"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revoked"): EventFragment;
}

export interface ReceivedEtherEventObject {
  sender: string;
  amount: BigNumber;
}
export type ReceivedEtherEvent = TypedEvent<
  [string, BigNumber],
  ReceivedEtherEventObject
>;

export type ReceivedEtherEventFilter = TypedEventFilter<ReceivedEtherEvent>;

export interface ReceivedTokensEventObject {
  from: string;
  value: BigNumber;
  token: string;
  extraData: string;
}
export type ReceivedTokensEvent = TypedEvent<
  [string, BigNumber, string, string],
  ReceivedTokensEventObject
>;

export type ReceivedTokensEventFilter = TypedEventFilter<ReceivedTokensEvent>;

export interface RevokedEventObject {
  revoked: boolean;
}
export type RevokedEvent = TypedEvent<[boolean], RevokedEventObject>;

export type RevokedEventFilter = TypedEventFilter<RevokedEvent>;

export interface AuthenticatedProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AuthenticatedProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    initialize(
      addrUser: PromiseOrValue<string>,
      addrRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    proxy(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    proxyAssert(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    receiveApproval(
      from: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    revoked(overrides?: CallOverrides): Promise<[boolean]>;

    setRevoke(
      revoke: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeabilityOwner(overrides?: CallOverrides): Promise<[string]>;

    user(overrides?: CallOverrides): Promise<[string]>;
  };

  initialize(
    addrUser: PromiseOrValue<string>,
    addrRegistry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  proxy(
    dest: PromiseOrValue<string>,
    howToCall: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  proxyAssert(
    dest: PromiseOrValue<string>,
    howToCall: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  receiveApproval(
    from: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registry(overrides?: CallOverrides): Promise<string>;

  revoked(overrides?: CallOverrides): Promise<boolean>;

  setRevoke(
    revoke: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeabilityOwner(overrides?: CallOverrides): Promise<string>;

  user(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    initialize(
      addrUser: PromiseOrValue<string>,
      addrRegistry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    proxy(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proxyAssert(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    receiveApproval(
      from: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    registry(overrides?: CallOverrides): Promise<string>;

    revoked(overrides?: CallOverrides): Promise<boolean>;

    setRevoke(
      revoke: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeabilityOwner(overrides?: CallOverrides): Promise<string>;

    user(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ReceivedEther(address,uint256)"(
      sender?: PromiseOrValue<string> | null,
      amount?: null
    ): ReceivedEtherEventFilter;
    ReceivedEther(
      sender?: PromiseOrValue<string> | null,
      amount?: null
    ): ReceivedEtherEventFilter;

    "ReceivedTokens(address,uint256,address,bytes)"(
      from?: PromiseOrValue<string> | null,
      value?: null,
      token?: PromiseOrValue<string> | null,
      extraData?: null
    ): ReceivedTokensEventFilter;
    ReceivedTokens(
      from?: PromiseOrValue<string> | null,
      value?: null,
      token?: PromiseOrValue<string> | null,
      extraData?: null
    ): ReceivedTokensEventFilter;

    "Revoked(bool)"(revoked?: null): RevokedEventFilter;
    Revoked(revoked?: null): RevokedEventFilter;
  };

  estimateGas: {
    initialize(
      addrUser: PromiseOrValue<string>,
      addrRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    proxy(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    proxyAssert(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    receiveApproval(
      from: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    revoked(overrides?: CallOverrides): Promise<BigNumber>;

    setRevoke(
      revoke: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeabilityOwner(overrides?: CallOverrides): Promise<BigNumber>;

    user(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      addrUser: PromiseOrValue<string>,
      addrRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    proxy(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    proxyAssert(
      dest: PromiseOrValue<string>,
      howToCall: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    receiveApproval(
      from: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revoked(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setRevoke(
      revoke: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeabilityOwner(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    user(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
